### ISSUE TITLE
希望支持域名

### ISSUE THREAD

**Issue by mabangde** [hanbufei/isCdn#1]
提几点建议：
1. 优先从sources_data.json读取
2. 支持域名形式
3. 支持华为CDN、网宿CDN验证
4. IP 从ip 本地IP库中读取而不是在线接口（qqwry\ip2region\17monipdb.zip）

附上我整理的sources_data.json
[sources_data.json](https://github.com/hanbufei/isCdn/files/13069134/sources_data.json)

ipip库：http://cdn.ipip.net/17mon/17monipdb.zip

**Comment by hanbufei** [comment]
感谢老哥的建议和整理的数据

**Comment by hanbufei** [comment]
已完成1、3、4的优化。
关于第二点，只能说抱歉了，因为这个api定义为专门做ip分析的。
后续有可能的话，我会专门写一个针对域名的。
